### ISSUE TITLE
sometimes joined message is not coming 

### ISSUE THREAD

**Issue by amarlearning** [amarlearning/chat-rooms#3]
Whenever a new user joins the chat room, sometimes the joins message come and sometimes not.

**No `Join` message came this time**

![screenshot from 2018-10-12 01-08-19](https://user-images.githubusercontent.com/9383897/46829502-9f4cf780-cdbb-11e8-962f-a12e7debdca4.png)

**This time the `Join` message came**
![screenshot from 2018-10-12 01-08-42](https://user-images.githubusercontent.com/9383897/46829525-aaa02300-cdbb-11e8-9d50-5d40ab296684.png)

**Comment by rodrigoejcm** [comment]
is this fixed?
